// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimuladorContribuicaoAposentadoria.Data.Context;

namespace SimuladorContribuicaoAposentadoria.Data.Migrations
{
    [DbContext(typeof(SimuladorContribuicaoAposentadoriaContext))]
    partial class SimuladorContribuicaoAposentadoriaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "5.0.0-preview.6.20312.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SimuladorContribuicaoAposentadoria.Domain.Entities.Resultado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataUltimaContribuicao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("IdSimulacao")
                        .HasColumnType("uuid");

                    b.Property<double>("PercentualAplicadoParaCalculo")
                        .HasColumnType("double precision");

                    b.Property<int>("QuantidadeContribuicoesParaPagarIniciandoMesAtual")
                        .HasColumnType("integer");

                    b.Property<double>("ValorPagoMes")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("IdSimulacao")
                        .IsUnique();

                    b.ToTable("Resultado");
                });

            modelBuilder.Entity("SimuladorContribuicaoAposentadoria.Domain.Entities.Simulacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<int>("IdadeComQueComecouContribuicao")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Salario")
                        .HasColumnType("double precision");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Simulacao");
                });

            modelBuilder.Entity("SimuladorContribuicaoAposentadoria.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80838d6f-724b-4183-a0e5-03fdaffafb7a"),
                            Nome = "admin",
                            Senha = "123"
                        });
                });

            modelBuilder.Entity("SimuladorContribuicaoAposentadoria.Domain.Entities.Resultado", b =>
                {
                    b.HasOne("SimuladorContribuicaoAposentadoria.Domain.Entities.Simulacao", "Simulacao")
                        .WithOne("Resultado")
                        .HasForeignKey("SimuladorContribuicaoAposentadoria.Domain.Entities.Resultado", "IdSimulacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimuladorContribuicaoAposentadoria.Domain.Entities.Simulacao", b =>
                {
                    b.HasOne("SimuladorContribuicaoAposentadoria.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Simulacoes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
